CREATE TABLE dbo.GifLogs
(
	ID					INT IDENTITY (1,1)	NOT NULL,
	QTime				DATETIME	NOT NULL,
	QAgent				VARCHAR(64),
	gifQuery			VARCHAR(64),
	CONSTRAINT [PK_dbo.GifLogs] PRIMARY KEY CLUSTERED (ID ASC)
);